#!/bin/bash
#SBATCH --time=59:00:00
#SBATCH --mem=50G
#SBATCH --gres=gpu:1
#SBATCH --partition=singlegpu
#SBATCH --error=job.err
#SBATCH --output=job.out
. ~/.bashrc
#export TMPDIR=/scratch/$SLURM_JOB_ID
cd /home/knc6/Software/tb3py/tb3py/Surf
conda activate my_tb3
python surf_auto_multi.py 2>&1|tee out

