name: tb3py-action

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        conda install -y -c conda-forge julia
        python -m pip install --upgrade pip
        pip install flake8 pytest pycodestyle pydocstyle codecov pytest-cov coverage 
        python -m pip install numpy
        python setup.py install
        pytest tb3py/tests/test_ptop.py
        coverage run -m pytest tb3py/tests/test_ptop.py
        coverage report -m
        codecov --token="0e548bc4-a189-4eee-a74f-00c6f05d3388"

    - name: Lint
      run: |
        pip install flake8 pytest pycodestyle pydocstyle
        pycodestyle --ignore E203,W503 --exclude=tests tb3py
        pydocstyle --match-dir=core --match-dir=io --match-dir=io --match-dir=ai --match-dir=analysis --match-dir=db --match-dir=tasks --count tb3py
        flake8 --ignore E203,W503 --exclude=tests --statistics --count --exit-zero tb3py
    - name: Test with pytest
      run: |
        export DGLBACKEND=pytorch
        echo 'pip freeze'
        pip freeze
        # codecov
